import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Bình Blog",
    description: "Generated by create next app",
};

export default function RootTemplate({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            {children}
            <div>Def</div>
        </>
    );
}
